version: '3.8'
services:
  custom-nginx:
    build:
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"

  custom-apache:
    build:
      dockerfile: /home/ubuntu/TasksFromPlaysDev/Docker/Apache_Conf/Dockerfile
    ports:
      - "8080:8080"
