version: '3.8'
services:
  custom-nginx:
    build:
      context: /opt/TasksFromPlaysDev/Docker/Nginx_Conf/Task12
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"

  custom-apache:
    build:
      context: /opt/TasksFromPlaysDev/Docker/Apache_Conf
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
