version: '3.8'
services:
  custom-nginx:
    build:
      dockerfile: ./Nginx_Conf/Task12/Dockerfile
    ports:
      - "80:80"
      - "443:443"

  custom-apache:
    build:
      dockerfile: ./Apache_Conf/Dockerfile
    ports:
      - "8080:8080"
