version: '3.8'
services:
  custom-nginx:
    build: 
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./letsencrypt:/etc/letsencrypt
      - ./var/www:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf


  custom-apache:
    build:
      dockerfile: /home/ubuntu/TasksFromPlaysDev/Docker/Apache_Conf/Dockerfile
    ports:
      -"8080:8080"
    